/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoWidthOption: typeof import('./src/components/ExportExcel/components/AutoWidthOption.vue')['default']
    BookTypeOption: typeof import('./src/components/ExportExcel/components/BookTypeOption.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ExportExcel: typeof import('./src/components/ExportExcel/index.vue')['default']
    FilenameOption: typeof import('./src/components/ExportExcel/components/FilenameOption.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipHtml: typeof import('./src/components/TooltipHtml.vue')['default']
    UploadExcel: typeof import('./src/components/UploadExcel.vue')['default']
  }
}
